import { Redirect, useRouter } from "expo-router";
import { useCallback, useEffect, useMemo, useState } from "react";
import { Linking, ScrollView, Text, View } from "react-native";

import { api } from "@/src/api/client";
import { AdminPage } from "@/src/components/AdminPage";
import { Button, Card, EmptyState, ErrorState, KpiCard, ListRow, LoadingState, PillTabs, SearchField, SegmentedControl, Sheet, Table, TableCell, TableHeader, TableRow, TextField } from "@/src/components/ui";
import { useAuth } from "@/src/state/auth";
import { colors, spacing, type } from "@/src/theme/tokens";

type Filters = { floors: { id: string; name: string }[]; brands: { id: string; name: string }[]; salespeople: { id: string; full_name: string }[] };
type Dashboard = { kpis: { revenue: number; orders: number; aov: number; gross_sales: number; customers: number }; trend: { bucket: string; revenue: number }[]; floors: any[]; brands: any[]; products: any[]; customers: any[]; salespeople: any[]; referrals: any[] };
type Funnel = { stages: { key: string; label: string; count: number; conversion_pct: number; dropoff_pct: number; revenue: number }[] };
const PRESETS = [{ value: "today", label: "Today" }, { value: "yesterday", label: "Yesterday" }, { value: "last_7_days", label: "7D" }, { value: "last_15_days", label: "15D" }, { value: "last_30_days", label: "30D" }, { value: "this_month", label: "This month" }, { value: "last_month", label: "Last month" }, { value: "quarter", label: "Quarter" }, { value: "year", label: "Year" }, { value: "custom", label: "Custom" }];
const money = (n = 0) => `₹${Math.round(n).toLocaleString("en-IN")}`;

function RevenueBars({ points }: { points: Dashboard["trend"] }) {
  const max = Math.max(...points.map((p) => p.revenue), 1);
  if (!points.length) return <EmptyState title="No confirmed revenue in this period" subtitle="Adjust the date or floor filter to inspect another period." />;
  return <View testID="executive-revenue-trend" style={{ flexDirection: "row", alignItems: "flex-end", height: 150, gap: 6 }}>
    {points.slice(-14).map((p) => <View key={p.bucket} style={{ flex: 1, gap: 6, alignItems: "center" }}><View style={{ width: "100%", minHeight: 4, height: `${Math.max(4, p.revenue / max * 100)}%` as any, backgroundColor: colors.brand, borderRadius: 2 }} /><Text numberOfLines={1} style={type.caption}>{p.bucket.slice(-5)}</Text></View>)}
  </View>;
}

function FilterPicker({ label, value, items, onChange, testID }: { label: string; value: string; items: { id: string; name: string }[]; onChange: (id: string) => void; testID: string }) {
  const [open, setOpen] = useState(false); const [search, setSearch] = useState("");
  const selected = items.find((item) => item.id === value)?.name || `All ${label}`;
  const shown = items.filter((item) => item.name.toLowerCase().includes(search.toLowerCase()));
  return <><Button label={selected} size="sm" variant="secondary" onPress={() => setOpen(true)} testID={`${testID}-open`} /><Sheet visible={open} onClose={() => setOpen(false)} title={`Filter by ${label}`} variant="bottom" minHeight="55%" testID={`${testID}-sheet`}><View style={{ gap: spacing.sm, flex: 1 }}><SearchField value={search} onChangeText={setSearch} onClear={() => setSearch("")} placeholder={`Search ${label.toLowerCase()}…`} testID={`${testID}-search`} /><ListRow title={`All ${label}`} onPress={() => { onChange(""); setOpen(false); }} testID={`${testID}-all`} />{shown.map((item) => <ListRow key={item.id} title={item.name} onPress={() => { onChange(item.id); setOpen(false); }} testID={`${testID}-${item.id}`} />)}</View></Sheet></>;
}

export default function ExecutiveAnalytics() {
  const { staff } = useAuth(); const router = useRouter();
  const [filters, setFilters] = useState<Filters | null>(null); const [data, setData] = useState<Dashboard | null>(null); const [funnel, setFunnel] = useState<Funnel | null>(null); const [error, setError] = useState<string | null>(null);
  const [floor, setFloor] = useState("all"); const [brand, setBrand] = useState(""); const [salesperson, setSalesperson] = useState(""); const [referral, setReferral] = useState("all"); const [preset, setPreset] = useState("this_month"); const [granularity, setGranularity] = useState("month"); const [dateFrom, setDateFrom] = useState(""); const [dateTo, setDateTo] = useState("");
  const query = useMemo(() => new URLSearchParams({ floor_id: floor, preset, granularity, ...(brand ? { brand_id: brand } : {}), ...(salesperson ? { salesperson_id: salesperson } : {}), ...(referral !== "all" ? { referrer_type: referral } : {}), ...(preset === "custom" ? { date_from: dateFrom, date_to: dateTo } : {}) }).toString(), [floor, brand, salesperson, referral, preset, granularity, dateFrom, dateTo]);
  const exportData = async (format: "csv" | "xlsx" | "pdf") => { const url = await api.authenticatedUrl(`/executive-analytics/export?format=${format}&floor_id=${floor}&preset=${preset}`); await Linking.openURL(url); };
  const load = useCallback(() => { setError(null); setData(null); setFunnel(null); Promise.all([api.get<Dashboard>(`/executive-analytics/dashboard?${query}`), api.get<Funnel>(`/executive-analytics/funnel?${query}`)]).then(([dashboard, stages]) => { setData(dashboard); setFunnel(stages); }).catch((e: any) => setError(e.detail || "Could not load executive analytics")); }, [query]);
  useEffect(() => { api.get<Filters>("/executive-analytics/filters").then(setFilters).catch(() => setFilters({ floors: [], brands: [], salespeople: [] })); }, []);
  useEffect(() => { load(); }, [load]);
  if (staff && !["owner", "admin", "manager"].includes(staff.role)) return <Redirect href="/(admin)/dashboard" />;
  return <AdminPage title="Executive Analytics" subtitle="Confirmed and completed orders only · live business books" actions={<PillTabs testID="executive-granularity" value={granularity} onChange={setGranularity} options={[{ value: "day", label: "D" }, { value: "month", label: "M" }, { value: "quarter", label: "Q" }, { value: "year", label: "Y" }]} />}>
    <ScrollView contentContainerStyle={{ gap: spacing.lg, paddingBottom: spacing.xxxl }}>
      <View style={{ gap: spacing.sm }} testID="executive-global-filters"><SegmentedControl testID="executive-floor-filter" value={floor} onChange={setFloor} options={[{ value: "all", label: "All Floors" }, ...(filters?.floors || []).map((f) => ({ value: f.id, label: f.name }))]} /><PillTabs testID="executive-date-filter" value={preset} onChange={setPreset} options={PRESETS} /></View>
      <View style={{ flexDirection: "row", flexWrap: "wrap", gap: spacing.sm }} testID="executive-entity-filters"><FilterPicker label="Brands" value={brand} items={filters?.brands || []} onChange={setBrand} testID="executive-brand-filter" /><FilterPicker label="Salespeople" value={salesperson} items={(filters?.salespeople || []).map((s) => ({ id: s.id, name: s.full_name }))} onChange={setSalesperson} testID="executive-salesperson-filter" /><PillTabs testID="executive-referral-filter" value={referral} onChange={setReferral} options={[{ value: "all", label: "All referrals" }, { value: "architect", label: "Architect" }, { value: "interior_designer", label: "Interior Designer" }]} /></View>
      {preset === "custom" ? <View style={{ flexDirection: "row", gap: spacing.sm }} testID="executive-custom-date-range"><TextField label="From" value={dateFrom} onChangeText={setDateFrom} placeholder="2026-01-01" containerStyle={{ flex: 1 }} testID="executive-date-from" /><TextField label="To" value={dateTo} onChangeText={setDateTo} placeholder="2026-01-31" containerStyle={{ flex: 1 }} testID="executive-date-to" /></View> : null}
      <View style={{ flexDirection: "row", gap: spacing.sm, flexWrap: "wrap" }} testID="executive-export-actions"><Button label="CSV" size="sm" variant="secondary" onPress={() => exportData("csv")} testID="executive-export-csv" /><Button label="Excel" size="sm" variant="secondary" onPress={() => exportData("xlsx")} testID="executive-export-xlsx" /><Button label="PDF" size="sm" variant="secondary" onPress={() => exportData("pdf")} testID="executive-export-pdf" /></View>
      {error ? <ErrorState subtitle={error} onRetry={load} /> : null}
      {!error && !data ? <LoadingState label="Building live executive view…" /> : null}
      {data ? <>
        <View style={{ flexDirection: "row", flexWrap: "wrap", gap: spacing.sm }} testID="executive-kpis">
          <KpiCard label="Total Revenue" value={money(data.kpis.revenue)} style={{ flex: 1, minWidth: 150 }} /><KpiCard label="Confirmed Orders" value={String(data.kpis.orders)} style={{ flex: 1, minWidth: 130 }} /><KpiCard label="Average Order" value={money(data.kpis.aov)} style={{ flex: 1, minWidth: 150 }} /><KpiCard label="Customers" value={String(data.kpis.customers)} style={{ flex: 1, minWidth: 120 }} />
        </View>
        <Card testID="executive-trend-panel" style={{ gap: spacing.md }}><Text style={type.titleMd}>Revenue trend</Text><Text style={type.caption}>Live confirmed-order revenue for the selected period</Text><RevenueBars points={data.trend} /></Card>
        <Card testID="executive-funnel-panel" style={{ gap: spacing.md }}><Text style={type.titleMd}>Walk-in conversion funnel</Text><Text style={type.caption}>Conversion, drop-off, and confirmed revenue at every operational stage</Text>{!funnel ? <LoadingState label="Loading funnel…" /> : funnel.stages.map((stage) => <View key={stage.key} testID={`executive-funnel-${stage.key}`} style={{ flexDirection: "row", alignItems: "center", gap: spacing.sm, paddingVertical: spacing.sm, borderBottomWidth: 1, borderBottomColor: colors.divider }}><View style={{ flex: 1 }}><Text style={type.bodyStrong}>{stage.label}</Text><Text style={type.caption}>{stage.conversion_pct}% conversion · {stage.dropoff_pct}% drop-off</Text></View><View style={{ alignItems: "flex-end" }}><Text style={type.bodyStrong}>{stage.count}</Text><Text style={type.caption}>{money(stage.revenue)}</Text></View></View>)}</Card>
        <Card testID="executive-floor-panel" style={{ gap: spacing.md }}><Text style={type.titleMd}>Floor performance</Text><Table><TableHeader columns={[{ label: "Floor", flex: 2 }, { label: "Revenue", align: "right" }, { label: "Orders", align: "right" }]} />{data.floors.map((row, i) => <TableRow key={row.floor_id} isLast={i === data.floors.length - 1} onPress={() => setFloor(row.floor_id)} testID={`executive-floor-${row.floor_id}`}><TableCell flex={2}>{row.floor_id}</TableCell><TableCell align="right">{money(row.revenue)}</TableCell><TableCell align="right">{String(row.orders)}</TableCell></TableRow>)}</Table></Card>
        <Card testID="executive-brand-panel" style={{ gap: spacing.md }}><Text style={type.titleMd}>Brand performance</Text><Table><TableHeader columns={[{ label: "Brand", flex: 2 }, { label: "Revenue", align: "right" }, { label: "Qty", align: "right" }]} />{data.brands.map((row, i) => <TableRow key={row.brand_id || i} isLast={i === data.brands.length - 1} onPress={() => router.push(`/(admin)/sales-data/brands/${row.brand_id}` as any)} testID={`executive-brand-${row.brand_id}`}><TableCell flex={2}>{row.brand_name || "Unmapped"}</TableCell><TableCell align="right">{money(row.revenue)}</TableCell><TableCell align="right">{String(row.quantity)}</TableCell></TableRow>)}</Table></Card>
        <Card testID="executive-customer-panel" style={{ gap: spacing.md }}><Text style={type.titleMd}>Customer lifetime value</Text><Table><TableHeader columns={[{ label: "Customer", flex: 2 }, { label: "Lifetime revenue", align: "right" }, { label: "Orders", align: "right" }]} />{data.customers.map((row, i) => <TableRow key={row.customer_id} isLast={i === data.customers.length - 1} onPress={() => router.push(`/(admin)/customers/${row.customer_id}` as any)} testID={`executive-customer-${row.customer_id}`}><TableCell flex={2}>{row.name}</TableCell><TableCell align="right">{money(row.revenue)}</TableCell><TableCell align="right">{String(row.orders)}</TableCell></TableRow>)}</Table></Card>
        <Card testID="executive-salespeople-panel" style={{ gap: spacing.md }}><Text style={type.titleMd}>Salesperson performance</Text><Table><TableHeader columns={[{ label: "Salesperson", flex: 2 }, { label: "Revenue", align: "right" }, { label: "Orders", align: "right" }, { label: "Conv.", align: "right" }]} />{data.salespeople.map((row, i) => <TableRow key={row.salesperson_id} isLast={i === data.salespeople.length - 1} onPress={() => router.push(`/(admin)/sales-data/people/salespeople/${row.salesperson_id}` as any)} testID={`executive-salesperson-${row.salesperson_id}`}><TableCell flex={2}>{row.name}</TableCell><TableCell align="right">{money(row.revenue)}</TableCell><TableCell align="right">{String(row.orders)}</TableCell><TableCell align="right">{row.conversion_rate}%</TableCell></TableRow>)}</Table></Card>
        <Card testID="executive-referrals-panel" style={{ gap: spacing.md }}><Text style={type.titleMd}>Referral leaderboard</Text><Table><TableHeader columns={[{ label: "Partner", flex: 2 }, { label: "Revenue", align: "right" }, { label: "Orders", align: "right" }]} />{data.referrals.map((row, i) => <TableRow key={row.referrer_id} isLast={i === data.referrals.length - 1} onPress={() => router.push(`/(admin)/sales-data/people/referrers/${row.referrer_id}` as any)} testID={`executive-referrer-${row.referrer_id}`}><TableCell flex={2}>{row.name}</TableCell><TableCell align="right">{money(row.revenue)}</TableCell><TableCell align="right">{String(row.orders)}</TableCell></TableRow>)}</Table></Card>
      </> : null}
    </ScrollView>
  </AdminPage>;
}